### ISSUE TITLE
Refactor to support swagger-ui-express

### ISSUE THREAD

**Issue by dsmileyephe** [doriansmiley/serverless-tools#5]
Add swagger-ui-express to package.json
Refactor index.ts as follows:
```
// IMPORTANT: all routes that do not require JWT authentication must be declared ahead of registering the middleware with app.use
app.get('/', cors(), function (req, res) {
    res.status(200).send('Hello World! I am the tenants-api API ' +  process.env.API_VERSION);
});

const xssConfig = {
    stripIgnoreTag: true
};
app.use('/', new XSSController(xssConfig).register());

//setup route for documents
app.use('/docs/', cors(), swaggerUi.serveWithOptions({ redirect: false }), swaggerUi.setup(swaggerDocument));
```
Note what we are doing here is removing JWT validation from the health check and docs route.
Add boiler plate to the serverless yaml for the docs and health check:
```
HealthCheck:
        handler: src/index.handler
        events:
            - http:
                path: /
                method: get
                cors:
                    origin: '*'
                    headers:
                      - Content-Type
                      - Authorization
                      - x-amzn-trace-id
        warmup: true
        environment:
            STAGE: ${opt:stage}
            JWT_SECRET: ${opt:jwt-secret}
        vpc:
          securityGroupIds:
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:SecurityGroup
          subnetIds:
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:PrivateSubnet1
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:PrivateSubnet2
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:PrivateSubnet3
    Docs:
        handler: src/index.handler
        events:
            - http:
                path: /docs/{proxy+}
                method: get
                cors:
                    origin: '*'
                    headers:
                      - Content-Type
                      - Authorization
                      - x-amzn-trace-id
        warmup: true
        environment:
            STAGE: ${opt:stage}
            JWT_SECRET: ${opt:jwt-secret}
        vpc:
          securityGroupIds:
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:SecurityGroup
          subnetIds:
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:PrivateSubnet1
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:PrivateSubnet2
            - !ImportValue ${opt:networking-stack,'Zeus1-VPC'}:PrivateSubnet3
```
